### ISSUE TITLE
Getting permission denied 401

### ISSUE THREAD

**Issue by alon1samuel** [nateraw/huggingpics#11]
Getting this:

---------------------------------------------------------------------------
HTTPError                                 Traceback (most recent call last)
[<ipython-input-5-4695df4aa6fc>](https://localhost:8080/#) in <cell line: 6>()
      7     search_term_dir = data_dir / search_term
      8     search_term_dir.mkdir(exist_ok=True, parents=True)
----> 9     urls = get_image_urls_by_term(search_term)
     10     print(f"Saving images of {search_term} to {str(search_term_dir)}...")
     11     urls_to_image_folder(urls, search_term_dir)

1 frames
[/usr/local/lib/python3.10/dist-packages/requests/models.py](https://localhost:8080/#) in raise_for_status(self)
   1019 
   1020         if http_error_msg:
-> 1021             raise HTTPError(http_error_msg, response=self)
   1022 
   1023     def close(self):

HTTPError: 401 Client Error: PermissionDenied for url: https://huggingface.co/api/experimental/images/search?q=fringe+selfie&license=public&imageType=photo&count=150

anyone else has this?

**Comment by hst45** [comment]
I got the same error. Have you solved this?

**Comment by alon1samuel** [comment]
I haven't solved it yet... Searching to see if anyone else had a solution?
maybe @nateraw ?

**Comment by Benjoyo** [comment]
Same here

**Comment by nateraw** [comment]
Ah the service probably went down.  I don't work at hf anymore so don't have direct access to see.

I'll take a look this week - sorry folks.

**Comment by julien-c** [comment]
let me check internally – in the meantime better to use a different image search provider (or manual upload?)

**Comment by nateraw** [comment]
@julien-c do you have any stats on cost of that API's usage in recent days monthly? I can set it up myself and replace the mirror. I would guess it's negligible. bonus points if you email me the api file we had written for it 😬

**Comment by nateraw** [comment]
Having good luck with [this](https://github.com/gurugaurav/bing_image_downloader) free resource

```python
# ! pip install bing-image-downloader

from bing_image_downloader import downloader


query_string = "dog"
downloader.download(query_string, limit=100,  output_dir='dataset', adult_filter_off=True, force_replace=False, timeout=60, verbose=True)
```

**Comment by nateraw** [comment]
<img width="1311" alt="Screen Shot 2024-05-07 at 2 08 32 AM" src="https://github.com/nateraw/huggingpics/assets/32437151/7c3e961a-c197-40ef-bd4f-448233b26f9c">

On second thought, not a huge fan of these results. Will either mirror the original api or wait for it to be restored

**Comment by alon1samuel** [comment]
@nateraw  Is this an easy API to write? Maybe I can help set it up

**Comment by nateraw** [comment]
Yes it's just a wrapper around the [Bing images API](https://learn.microsoft.com/en-us/bing/search-apis/bing-image-search/quickstarts/rest/python) from Azure. 150 was a limit at some point, which is why in the notebook we limited to that. But perhaps (I can't remember) we also handled pagination stuff behind the scenes if you wanted more than 150.

The code you end up using to hit it in the notebook (HF link being the wrapper API we set up):

```
SEARCH_URL = "https://huggingface.co/api/experimental/images/search"

def get_image_urls_by_term(search_term: str, count=150):
    params  = {"q": search_term, "license": "public", "imageType": "photo", "count": count}
    response = requests.get(SEARCH_URL, params=params)
    response.raise_for_status()
    response_data = response.json()
    image_urls = [img['thumbnailUrl'] for img in response_data['value']]
    return image_urls
```

Should be simple enough. If you have a stab at it, lmk! else I'll do it when I find some time.

**Comment by nateraw** [comment]
Actually @alon1samuel I went ahead and did it. This issue should be resolved now. Someone feel free to check the notebook for me so I can close this :)

**Comment by Benjoyo** [comment]
> Actually @alon1samuel I went ahead and did it. This issue should be resolved now. Someone feel free to check the notebook for me so I can close this :)

It works :) Thank you

**Comment by julien-c** [comment]
(the HF wrapper was just adding an access token, not doing anything else)
