### ISSUE TITLE
Bing API quota exceed error

### ISSUE THREAD

**Issue by eriven** [nateraw/huggingpics#14]
While running the get image by url cell I got this error :
---------------------------------------------------------------------------
HTTPError                                 Traceback (most recent call last)
[<ipython-input-14-4695df4aa6fc>](https://localhost:8080/#) in <cell line: 6>()
      7     search_term_dir = data_dir / search_term
      8     search_term_dir.mkdir(exist_ok=True, parents=True)
----> 9     urls = get_image_urls_by_term(search_term)
     10     print(f"Saving images of {search_term} to {str(search_term_dir)}...")
     11     urls_to_image_folder(urls, search_term_dir)

1 frames
[/usr/local/lib/python3.10/dist-packages/requests/models.py](https://localhost:8080/#) in raise_for_status(self)
   1022 
   1023         if http_error_msg:
-> 1024             raise HTTPError(http_error_msg, response=self)
   1025 
   1026     def close(self):

HTTPError: 500 Server Error: Internal Server Error for url: https://huggingpics-api-server.fly.dev/images/search?q=WaterBottle&license=public&imageType=photo&count=5

On clicking the error detail link it says bing api quota exceed , but I haven't even run it once.

**Comment by nateraw** [comment]
I switched to free bing API tier because I was getting charged for this project every month...if I could get some credits/sponsorship here I could turn it back on paid tier so these quota issues won't come up 🙁 sorry about that

**Comment by eriven** [comment]
> I switched to free bing API tier because I was getting charged for this project every month...if I could get some credits/sponsorship here I could turn it back on paid tier so these quota issues won't come up 🙁 sorry about that
