### ISSUE TITLE
Issue fitting the model - RuntimeError: Found dtype Long but expected Float

### ISSUE THREAD

**Issue by Infinitay** [nateraw/huggingpics#2]
I'm having an issue on fitting the model. Given your example, HuggingPics works just fine. However, when I attempted to train my own model with one class with `iron man`, I am having issues under the Training section, cell 2, in particular
```py
pl.seed_everything(42)
classifier = Classifier(model, lr=2e-5)
trainer = pl.Trainer(gpus=1, precision=16, max_epochs=4)
trainer.fit(classifier, train_loader, val_loader) # ERROR HERE
```

I tried to pin point the issue, but it was to no avail. First, I attempted to convert the encoding to a float in `ImageClassificationCollator`. However, that threw a new error for the same line,

> ValueError: The `target` has to be an integer tensor.

I thought the error could be because of not enough classes, but that wasn't the case. I also thought it was because there wasn't enough data, but I I lowered the image count and your example processed fine.

**Comment by nateraw** [comment]
mind sharing the colab notebook here?
