### ISSUE TITLE
problem when downloading images of class

### ISSUE THREAD

**Issue by abdullahmoosa** [nateraw/huggingpics#5]
Hey, I am a newbie but I was trying to run the colab file (the default one). So then I came up with this error:

![Screenshot (8)](https://user-images.githubusercontent.com/67234038/151788706-190cf90f-35c3-4ef6-a312-f67ce7bb624d.png)

**Comment by nateraw** [comment]
Looking into this, its definitely nothing you did wrong. Thanks a lot for reporting!!
