### ISSUE TITLE
Image search returns max 35 results

### ISSUE THREAD

**Issue by dumbshow** [nateraw/huggingpics#6]
Hi,

The image search at https://huggingface.co/api/experimental/images/search returns max 35 results.  Values lower than 35 in the "count" parameter are honored; values above 35 are ignored and 35 results are returned.  Your great tutorial suggests that 150 results can be gathered through this API for each query.  Has the image search API changed?  Thank you!

**Comment by nateraw** [comment]
Will take a look when I have a chance later this week/early next week. thanks for reporting.

**Comment by julien-c** [comment]
hmm for me `https://huggingface.co/api/experimental/images/search?q=corgi&count=150` returns 150 hits, could it be that something specific happening with you `q` term?

**Comment by nateraw** [comment]
@julien-c yea this sounds right to me too. @dumbshow do you remember the query you were using?

**Comment by dumbshow** [comment]
Yes, it must have been that.  I am seeing 150 results for the "corgi" query above.
Apologies for the false alarm.  Thanks to both of you for the help.
