### ISSUE TITLE
Can't instantiate abstract class Classifier with abstract methods forward

### ISSUE THREAD

**Issue by e-choness** [nateraw/huggingpics#7]
Hi

Thank you for this straight forward codes for us to practice fine-tuning models with ViT. I'm on a project that classifying book covers. Everything goes well on my own dataset until trying to define classifier. An error message popped up "Can't instantiate abstract class Classifier with abstract methods forward".  As I looked up the pytorch lightning code about forward(), it is indeed an abstract class. No idea why the error since the method was initiated in the __init__() method.

![image](https://user-images.githubusercontent.com/52640068/189777416-204dab4a-db08-430d-94f5-e18f401baff8.png)

Has anyone run into this issue yet?

**Comment by nateraw** [comment]
If I were you I would create a new environment, reinstall latest pypi of pytorch-lightning, and see if that solves your issue. I just re-ran the colab notebook and its fine, so there's got to be something wrong with your local environment.

**Comment by e-choness** [comment]
> If I were you I would create a new environment, reinstall latest pypi of pytorch-lightning, and see if that solves your issue. I just re-ran the colab notebook and its fine, so there's got to be something wrong with your local environment.

Thank you for the quick reply. I installed pytorch-lightning just a few days ago. The issue might be my outdated transformer package. I will try it out and return with the results.

**Comment by nateraw** [comment]
sounds good! I do think its lightning, though. My guess is a `pip install -U pytorch-lightning` would fix this.

**Comment by e-choness** [comment]
> sounds good! I do think its lightning, though. My guess is a `pip install -U pytorch-lightning` would fix this.

Thank you! Updated both transformer and pytorch-lightning package. It's no longer an issue. But another one rised.

![image](https://user-images.githubusercontent.com/52640068/189783849-7a0df93e-2a20-4f9b-91d1-3caea5f42cf8.png)

Guess a lot of my installed packages are a bit outdated. Anyway, much appreciated with the solution. Spot on!

**Comment by nateraw** [comment]
Great! glad it worked out for you. And yea, the gpu stuff should be updated to whatever the latest syntax is. Closing this now - cheers.
